version: '3'
services:
  amqp:
    image: rabbitmq:3.7-alpine
    ports:
      - 5672:5672
  
  local-management-service:
    build: ./local-management-service
    volumes:
      - ./local-management-service/sources.conf:/HINC/local-management-service/target/sources.conf 
  
  global-management-service:
    build: ./global-management-service
    ports:
      - 9000:9000
