version: '3'
services:
  amqp:
    image: rabbitmq:3.7-alpine
    ports:
      - 5672:5672
      - 15672:15672
  
  local-management-service:
    build: ./local-management-service
    volumes:
      - ./local-management-service/sources.conf:/HINC/local-management-service/target/sources.conf 
      - ./local-management-service/hinc.conf:/HINC/local-management-service/target/hinc.conf
      - ./local-management-service/wait-for-it.sh:/HINC/local-management-service/target/wait-for-it.sh
      - ./local-management-service/plugins:/HINC/local-management-service/target/plugins
    depends_on: 
      - amqp
  
  global-management-service:
    build: ./global-management-service
    ports:
      - 9000:9000
    depends_on:
      - amqp
