swagger: "3.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "rsiHub - Interoperability Service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/interoperability"
tags:
- name: "check"
  description: "Interoperability Check"
  #externalDocs:
  #  description: "Find out more"
    #url: "http://swagger.io"
- name: "recommendation"
  description: "Interoperability Recommendation"
  #externalDocs:
  #  description: "Find out more"
    #url: "http://swagger.io"

schemes:
- "http"
paths:
  /check:
    post:
      tags:
      - "check"
      summary: "Perform an interoperability check on the slice"
      description: ""
      operationId: "check"
      consumes:
      - "application/json"
      produces: ["application/json"]
      parameters:
      - in: "body"
        name: "body"
        description: "The resource slice that the interoperability check is performed on"
        required: true
        schema:
          $ref: "#/definitions/Slice"
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
  /recommendation:
    post:
      tags:
      - "recommendation"
      summary: "Get the interoperability recommendation for the slice"
      description: ""
      operationId: "recommendation"
      consumes:
      - "application/json"
      produces: ["application/json"]
      parameters:
      - in: "body"
        name: "body"
        description: "The resource slice that the interoperability recommendation is based on"
        required: true
        schema:
          $ref: "#/definitions/Slice"
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
definitions:
  Slice:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "testname"
      photoUrls:
        type: "array"
        items:
          type: "string"
      tags:
        type: "array"
        items:
          type: "string"
          format: "date-time"
      status:
        type: "string"
        description: "pet status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"