version: '3'
services:
  rabbitmq:
   image: rabbitmq:3.7-management-alpine
   container_name: rabbitmq
   hostname: rabbitmq
   ports: 
     - 15672:15672
networks:
  default:
   external:
    name: mybridge

    
